[workspace]
members = [
    "autosar-data",
    "autosar-data-specification",
]
resolver = "2"

[patch.crates-io]
autosar-data = { path = "autosar-data" }
autosar-data-specification = { path = "./autosar-data-specification" }
